#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBMSQuanTraSua
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanTraSua")]
	public partial class DBMSQuanTraSuaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTB_ChiTietHoaDon(TB_ChiTietHoaDon instance);
    partial void UpdateTB_ChiTietHoaDon(TB_ChiTietHoaDon instance);
    partial void DeleteTB_ChiTietHoaDon(TB_ChiTietHoaDon instance);
    partial void InsertTB_TaiKhoan(TB_TaiKhoan instance);
    partial void UpdateTB_TaiKhoan(TB_TaiKhoan instance);
    partial void DeleteTB_TaiKhoan(TB_TaiKhoan instance);
    partial void InsertTB_ChiTietNguyenLieu(TB_ChiTietNguyenLieu instance);
    partial void UpdateTB_ChiTietNguyenLieu(TB_ChiTietNguyenLieu instance);
    partial void DeleteTB_ChiTietNguyenLieu(TB_ChiTietNguyenLieu instance);
    partial void InsertTB_DonVi(TB_DonVi instance);
    partial void UpdateTB_DonVi(TB_DonVi instance);
    partial void DeleteTB_DonVi(TB_DonVi instance);
    partial void InsertTB_HoaDon(TB_HoaDon instance);
    partial void UpdateTB_HoaDon(TB_HoaDon instance);
    partial void DeleteTB_HoaDon(TB_HoaDon instance);
    partial void InsertTB_KhachHang(TB_KhachHang instance);
    partial void UpdateTB_KhachHang(TB_KhachHang instance);
    partial void DeleteTB_KhachHang(TB_KhachHang instance);
    partial void InsertTB_LoaiSanPham(TB_LoaiSanPham instance);
    partial void UpdateTB_LoaiSanPham(TB_LoaiSanPham instance);
    partial void DeleteTB_LoaiSanPham(TB_LoaiSanPham instance);
    partial void InsertTB_NguyenLieu(TB_NguyenLieu instance);
    partial void UpdateTB_NguyenLieu(TB_NguyenLieu instance);
    partial void DeleteTB_NguyenLieu(TB_NguyenLieu instance);
    partial void InsertTB_NhanVien(TB_NhanVien instance);
    partial void UpdateTB_NhanVien(TB_NhanVien instance);
    partial void DeleteTB_NhanVien(TB_NhanVien instance);
    partial void InsertTB_Quay(TB_Quay instance);
    partial void UpdateTB_Quay(TB_Quay instance);
    partial void DeleteTB_Quay(TB_Quay instance);
    partial void InsertTB_SanPham(TB_SanPham instance);
    partial void UpdateTB_SanPham(TB_SanPham instance);
    partial void DeleteTB_SanPham(TB_SanPham instance);
    #endregion
		
		public DBMSQuanTraSuaDataContext() : 
				base(global::DBMSQuanTraSua.Properties.Settings.Default.QuanTraSuaConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DBMSQuanTraSuaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMSQuanTraSuaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMSQuanTraSuaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMSQuanTraSuaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TB_ChiTietHoaDon> TB_ChiTietHoaDons
		{
			get
			{
				return this.GetTable<TB_ChiTietHoaDon>();
			}
		}
		
		public System.Data.Linq.Table<TB_TaiKhoan> TB_TaiKhoans
		{
			get
			{
				return this.GetTable<TB_TaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<TB_ChiTietNguyenLieu> TB_ChiTietNguyenLieus
		{
			get
			{
				return this.GetTable<TB_ChiTietNguyenLieu>();
			}
		}
		
		public System.Data.Linq.Table<TB_DonVi> TB_DonVis
		{
			get
			{
				return this.GetTable<TB_DonVi>();
			}
		}
		
		public System.Data.Linq.Table<TB_HoaDon> TB_HoaDons
		{
			get
			{
				return this.GetTable<TB_HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<TB_KhachHang> TB_KhachHangs
		{
			get
			{
				return this.GetTable<TB_KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<TB_LoaiSanPham> TB_LoaiSanPhams
		{
			get
			{
				return this.GetTable<TB_LoaiSanPham>();
			}
		}
		
		public System.Data.Linq.Table<TB_NguyenLieu> TB_NguyenLieus
		{
			get
			{
				return this.GetTable<TB_NguyenLieu>();
			}
		}
		
		public System.Data.Linq.Table<TB_NhanVien> TB_NhanViens
		{
			get
			{
				return this.GetTable<TB_NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<TB_Quay> TB_Quays
		{
			get
			{
				return this.GetTable<TB_Quay>();
			}
		}
		
		public System.Data.Linq.Table<TB_SanPham> TB_SanPhams
		{
			get
			{
				return this.GetTable<TB_SanPham>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspChoNghiViec")]
		public int uspChoNghiViec([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNhanVien", DbType="NVarChar(30)")] string maNhanVien)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maNhanVien);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspXoaNhanVien")]
		public int uspXoaNhanVien([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNhanVien", DbType="NVarChar(10)")] string maNhanVien)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maNhanVien);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspDoiMatKhau")]
		public int uspDoiMatKhau([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string forlogin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string newpass)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), forlogin, newpass);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspGiaiMaChuoi")]
		public int uspGiaiMaChuoi([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string inputstring, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] ref string outputstring)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), inputstring, outputstring);
			outputstring = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspMaHoaChuoi")]
		public int uspMaHoaChuoi([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string inputstring, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] ref string outputstring)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), inputstring, outputstring);
			outputstring = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspSuaNhanVien")]
		public int uspSuaNhanVien([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNhanVien", DbType="NVarChar(10)")] string maNhanVien, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoTen", DbType="NVarChar(30)")] string hoTen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GioiTinh", DbType="NVarChar(30)")] string gioiTinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgaySinh", DbType="Date")] System.Nullable<System.DateTime> ngaySinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CMND", DbType="NVarChar(30)")] string cMND, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoDienThoai", DbType="NVarChar(30)")] string soDienThoai, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiaChi", DbType="NVarChar(30)")] string diaChi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgayVaoLam", DbType="Date")] System.Nullable<System.DateTime> ngayVaoLam, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChucVu", DbType="NVarChar(30)")] string chucVu, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MucLuong", DbType="NVarChar(30)")] string mucLuong, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaQuay", DbType="NVarChar(10)")] string maQuay)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maNhanVien, hoTen, gioiTinh, ngaySinh, cMND, soDienThoai, diaChi, ngayVaoLam, chucVu, mucLuong, maQuay);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspTachChuoi")]
		public int uspTachChuoi([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string inputstring, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> outputvalue1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> outputvalue2)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), inputstring, outputvalue1, outputvalue2);
			outputvalue1 = ((System.Nullable<int>)(result.GetParameterValue(1)));
			outputvalue2 = ((System.Nullable<int>)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspTaoTaiKhoanSQL")]
		public int uspTaoTaiKhoanSQL([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string login, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string role)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), login, password, role);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspThangChuc")]
		public int uspThangChuc([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNhanVien", DbType="NVarChar(30)")] string maNhanVien)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maNhanVien);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspThemNhanVien")]
		public int uspThemNhanVien([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNhanVien", DbType="NVarChar(10)")] string maNhanVien, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoTen", DbType="NVarChar(30)")] string hoTen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GioiTinh", DbType="NVarChar(30)")] string gioiTinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgaySinh", DbType="Date")] System.Nullable<System.DateTime> ngaySinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CMND", DbType="NVarChar(30)")] string cMND, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoDienThoai", DbType="NVarChar(30)")] string soDienThoai, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiaChi", DbType="NVarChar(30)")] string diaChi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgayVaoLam", DbType="Date")] System.Nullable<System.DateTime> ngayVaoLam, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChucVu", DbType="NVarChar(30)")] string chucVu, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MucLuong", DbType="NVarChar(30)")] string mucLuong, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaQuay", DbType="NVarChar(10)")] string maQuay, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TamKhoa", DbType="Bit")] System.Nullable<bool> tamKhoa)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maNhanVien, hoTen, gioiTinh, ngaySinh, cMND, soDienThoai, diaChi, ngayVaoLam, chucVu, mucLuong, maQuay, tamKhoa);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspTinhThoiGianLamViecTaiQuan", IsComposable=true)]
		public object uspTinhThoiGianLamViecTaiQuan([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string inputMaNhanVien, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] ref string kq)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), inputMaNhanVien, kq);
			kq = ((string)(result.GetParameterValue(1)));
			return ((object)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ufuDemSoNhanVienConLamViec", IsComposable=true)]
		public System.Nullable<int> ufuDemSoNhanVienConLamViec()
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ufuTinhTienThuTheoThang", IsComposable=true)]
		public System.Nullable<int> ufuTinhTienThuTheoThang([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> inputnam, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> inputthang)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), inputnam, inputthang).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ufuLayHoaDon", IsComposable=true)]
		public IQueryable<ufuLayHoaDonResult> ufuLayHoaDon()
		{
			return this.CreateMethodCallQuery<ufuLayHoaDonResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ufuLocHoaDon", IsComposable=true)]
		public IQueryable<ufuLocHoaDonResult> ufuLocHoaDon([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> inputvalue1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> inputvalue2)
		{
			return this.CreateMethodCallQuery<ufuLocHoaDonResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), inputvalue1, inputvalue2);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ufuThongKeDoanhThuThang", IsComposable=true)]
		public IQueryable<ufuThongKeDoanhThuThangResult> ufuThongKeDoanhThuThang([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> inputyear)
		{
			return this.CreateMethodCallQuery<ufuThongKeDoanhThuThangResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), inputyear);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspThemHoaDon")]
		public int uspThemHoaDon([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHoaDon", DbType="NVarChar(10)")] string maHoaDon, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNhanVien", DbType="NVarChar(30)")] string maNhanVien, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaKhachHang", DbType="NVarChar(30)")] string maKhachHang, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TongTien", DbType="Int")] System.Nullable<int> tongTien)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHoaDon, maNhanVien, maKhachHang, tongTien);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ufuTimKiemNhanVienTheoTen", IsComposable=true)]
		public IQueryable<ufuTimKiemNhanVienTheoTenResult> ufuTimKiemNhanVienTheoTen([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string input)
		{
			return this.CreateMethodCallQuery<ufuTimKiemNhanVienTheoTenResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), input);
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_ChiTietHoaDon")]
	public partial class TB_ChiTietHoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHoaDon;
		
		private string _MaSanPham;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<int> _ThanhTien;
		
		private EntityRef<TB_HoaDon> _TB_HoaDon;
		
		private EntityRef<TB_SanPham> _TB_SanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHoaDonChanging(string value);
    partial void OnMaHoaDonChanged();
    partial void OnMaSanPhamChanging(string value);
    partial void OnMaSanPhamChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnThanhTienChanging(System.Nullable<int> value);
    partial void OnThanhTienChanged();
    #endregion
		
		public TB_ChiTietHoaDon()
		{
			this._TB_HoaDon = default(EntityRef<TB_HoaDon>);
			this._TB_SanPham = default(EntityRef<TB_SanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoaDon", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHoaDon
		{
			get
			{
				return this._MaHoaDon;
			}
			set
			{
				if ((this._MaHoaDon != value))
				{
					if (this._TB_HoaDon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHoaDonChanging(value);
					this.SendPropertyChanging();
					this._MaHoaDon = value;
					this.SendPropertyChanged("MaHoaDon");
					this.OnMaHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSanPham", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSanPham
		{
			get
			{
				return this._MaSanPham;
			}
			set
			{
				if ((this._MaSanPham != value))
				{
					if (this._TB_SanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSanPhamChanging(value);
					this.SendPropertyChanging();
					this._MaSanPham = value;
					this.SendPropertyChanged("MaSanPham");
					this.OnMaSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Int")]
		public System.Nullable<int> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this.OnThanhTienChanging(value);
					this.SendPropertyChanging();
					this._ThanhTien = value;
					this.SendPropertyChanged("ThanhTien");
					this.OnThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_HoaDon_TB_ChiTietHoaDon", Storage="_TB_HoaDon", ThisKey="MaHoaDon", OtherKey="MaHoaDon", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public TB_HoaDon TB_HoaDon
		{
			get
			{
				return this._TB_HoaDon.Entity;
			}
			set
			{
				TB_HoaDon previousValue = this._TB_HoaDon.Entity;
				if (((previousValue != value) 
							|| (this._TB_HoaDon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_HoaDon.Entity = null;
						previousValue.TB_ChiTietHoaDons.Remove(this);
					}
					this._TB_HoaDon.Entity = value;
					if ((value != null))
					{
						value.TB_ChiTietHoaDons.Add(this);
						this._MaHoaDon = value.MaHoaDon;
					}
					else
					{
						this._MaHoaDon = default(string);
					}
					this.SendPropertyChanged("TB_HoaDon");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_SanPham_TB_ChiTietHoaDon", Storage="_TB_SanPham", ThisKey="MaSanPham", OtherKey="MaSanPham", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public TB_SanPham TB_SanPham
		{
			get
			{
				return this._TB_SanPham.Entity;
			}
			set
			{
				TB_SanPham previousValue = this._TB_SanPham.Entity;
				if (((previousValue != value) 
							|| (this._TB_SanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_SanPham.Entity = null;
						previousValue.TB_ChiTietHoaDons.Remove(this);
					}
					this._TB_SanPham.Entity = value;
					if ((value != null))
					{
						value.TB_ChiTietHoaDons.Add(this);
						this._MaSanPham = value.MaSanPham;
					}
					else
					{
						this._MaSanPham = default(string);
					}
					this.SendPropertyChanged("TB_SanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_TaiKhoan")]
	public partial class TB_TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private string _MaNhanVien;
		
		private string _VaiTro;
		
		private System.Nullable<bool> _TamKhoa;
		
		private EntityRef<TB_NhanVien> _TB_NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnMaNhanVienChanging(string value);
    partial void OnMaNhanVienChanged();
    partial void OnVaiTroChanging(string value);
    partial void OnVaiTroChanged();
    partial void OnTamKhoaChanging(System.Nullable<bool> value);
    partial void OnTamKhoaChanged();
    #endregion
		
		public TB_TaiKhoan()
		{
			this._TB_NhanVien = default(EntityRef<TB_NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="NVarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="NVarChar(10)")]
		public string MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					if (this._TB_NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VaiTro", DbType="NVarChar(30)")]
		public string VaiTro
		{
			get
			{
				return this._VaiTro;
			}
			set
			{
				if ((this._VaiTro != value))
				{
					this.OnVaiTroChanging(value);
					this.SendPropertyChanging();
					this._VaiTro = value;
					this.SendPropertyChanged("VaiTro");
					this.OnVaiTroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TamKhoa", DbType="Bit")]
		public System.Nullable<bool> TamKhoa
		{
			get
			{
				return this._TamKhoa;
			}
			set
			{
				if ((this._TamKhoa != value))
				{
					this.OnTamKhoaChanging(value);
					this.SendPropertyChanging();
					this._TamKhoa = value;
					this.SendPropertyChanged("TamKhoa");
					this.OnTamKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_NhanVien_TB_TaiKhoan", Storage="_TB_NhanVien", ThisKey="MaNhanVien", OtherKey="MaNhanVien", IsForeignKey=true, DeleteRule="SET NULL")]
		public TB_NhanVien TB_NhanVien
		{
			get
			{
				return this._TB_NhanVien.Entity;
			}
			set
			{
				TB_NhanVien previousValue = this._TB_NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._TB_NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_NhanVien.Entity = null;
						previousValue.TB_TaiKhoans.Remove(this);
					}
					this._TB_NhanVien.Entity = value;
					if ((value != null))
					{
						value.TB_TaiKhoans.Add(this);
						this._MaNhanVien = value.MaNhanVien;
					}
					else
					{
						this._MaNhanVien = default(string);
					}
					this.SendPropertyChanged("TB_NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_ChiTietNguyenLieu")]
	public partial class TB_ChiTietNguyenLieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSanPham;
		
		private string _MaNguyenLieu;
		
		private System.Nullable<int> _SoLuong;
		
		private EntityRef<TB_NguyenLieu> _TB_NguyenLieu;
		
		private EntityRef<TB_SanPham> _TB_SanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSanPhamChanging(string value);
    partial void OnMaSanPhamChanged();
    partial void OnMaNguyenLieuChanging(string value);
    partial void OnMaNguyenLieuChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    #endregion
		
		public TB_ChiTietNguyenLieu()
		{
			this._TB_NguyenLieu = default(EntityRef<TB_NguyenLieu>);
			this._TB_SanPham = default(EntityRef<TB_SanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSanPham", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSanPham
		{
			get
			{
				return this._MaSanPham;
			}
			set
			{
				if ((this._MaSanPham != value))
				{
					if (this._TB_SanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSanPhamChanging(value);
					this.SendPropertyChanging();
					this._MaSanPham = value;
					this.SendPropertyChanged("MaSanPham");
					this.OnMaSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguyenLieu", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNguyenLieu
		{
			get
			{
				return this._MaNguyenLieu;
			}
			set
			{
				if ((this._MaNguyenLieu != value))
				{
					if (this._TB_NguyenLieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNguyenLieuChanging(value);
					this.SendPropertyChanging();
					this._MaNguyenLieu = value;
					this.SendPropertyChanged("MaNguyenLieu");
					this.OnMaNguyenLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_NguyenLieu_TB_ChiTietNguyenLieu", Storage="_TB_NguyenLieu", ThisKey="MaNguyenLieu", OtherKey="MaNguyenLieu", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public TB_NguyenLieu TB_NguyenLieu
		{
			get
			{
				return this._TB_NguyenLieu.Entity;
			}
			set
			{
				TB_NguyenLieu previousValue = this._TB_NguyenLieu.Entity;
				if (((previousValue != value) 
							|| (this._TB_NguyenLieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_NguyenLieu.Entity = null;
						previousValue.TB_ChiTietNguyenLieus.Remove(this);
					}
					this._TB_NguyenLieu.Entity = value;
					if ((value != null))
					{
						value.TB_ChiTietNguyenLieus.Add(this);
						this._MaNguyenLieu = value.MaNguyenLieu;
					}
					else
					{
						this._MaNguyenLieu = default(string);
					}
					this.SendPropertyChanged("TB_NguyenLieu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_SanPham_TB_ChiTietNguyenLieu", Storage="_TB_SanPham", ThisKey="MaSanPham", OtherKey="MaSanPham", IsForeignKey=true)]
		public TB_SanPham TB_SanPham
		{
			get
			{
				return this._TB_SanPham.Entity;
			}
			set
			{
				TB_SanPham previousValue = this._TB_SanPham.Entity;
				if (((previousValue != value) 
							|| (this._TB_SanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_SanPham.Entity = null;
						previousValue.TB_ChiTietNguyenLieus.Remove(this);
					}
					this._TB_SanPham.Entity = value;
					if ((value != null))
					{
						value.TB_ChiTietNguyenLieus.Add(this);
						this._MaSanPham = value.MaSanPham;
					}
					else
					{
						this._MaSanPham = default(string);
					}
					this.SendPropertyChanged("TB_SanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_DonVi")]
	public partial class TB_DonVi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDonVi;
		
		private string _TenDonVi;
		
		private EntitySet<TB_NguyenLieu> _TB_NguyenLieus;
		
		private EntitySet<TB_SanPham> _TB_SanPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDonViChanging(string value);
    partial void OnMaDonViChanged();
    partial void OnTenDonViChanging(string value);
    partial void OnTenDonViChanged();
    #endregion
		
		public TB_DonVi()
		{
			this._TB_NguyenLieus = new EntitySet<TB_NguyenLieu>(new Action<TB_NguyenLieu>(this.attach_TB_NguyenLieus), new Action<TB_NguyenLieu>(this.detach_TB_NguyenLieus));
			this._TB_SanPhams = new EntitySet<TB_SanPham>(new Action<TB_SanPham>(this.attach_TB_SanPhams), new Action<TB_SanPham>(this.detach_TB_SanPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonVi", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDonVi
		{
			get
			{
				return this._MaDonVi;
			}
			set
			{
				if ((this._MaDonVi != value))
				{
					this.OnMaDonViChanging(value);
					this.SendPropertyChanging();
					this._MaDonVi = value;
					this.SendPropertyChanged("MaDonVi");
					this.OnMaDonViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDonVi", DbType="NVarChar(30)")]
		public string TenDonVi
		{
			get
			{
				return this._TenDonVi;
			}
			set
			{
				if ((this._TenDonVi != value))
				{
					this.OnTenDonViChanging(value);
					this.SendPropertyChanging();
					this._TenDonVi = value;
					this.SendPropertyChanged("TenDonVi");
					this.OnTenDonViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_DonVi_TB_NguyenLieu", Storage="_TB_NguyenLieus", ThisKey="MaDonVi", OtherKey="MaDonVi")]
		public EntitySet<TB_NguyenLieu> TB_NguyenLieus
		{
			get
			{
				return this._TB_NguyenLieus;
			}
			set
			{
				this._TB_NguyenLieus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_DonVi_TB_SanPham", Storage="_TB_SanPhams", ThisKey="MaDonVi", OtherKey="MaDonVi")]
		public EntitySet<TB_SanPham> TB_SanPhams
		{
			get
			{
				return this._TB_SanPhams;
			}
			set
			{
				this._TB_SanPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_NguyenLieus(TB_NguyenLieu entity)
		{
			this.SendPropertyChanging();
			entity.TB_DonVi = this;
		}
		
		private void detach_TB_NguyenLieus(TB_NguyenLieu entity)
		{
			this.SendPropertyChanging();
			entity.TB_DonVi = null;
		}
		
		private void attach_TB_SanPhams(TB_SanPham entity)
		{
			this.SendPropertyChanging();
			entity.TB_DonVi = this;
		}
		
		private void detach_TB_SanPhams(TB_SanPham entity)
		{
			this.SendPropertyChanging();
			entity.TB_DonVi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_HoaDon")]
	public partial class TB_HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHoaDon;
		
		private string _MaNhanVien;
		
		private string _MaKhachHang;
		
		private System.Nullable<System.DateTime> _ThoiGian;
		
		private System.Nullable<int> _TongTien;
		
		private EntitySet<TB_ChiTietHoaDon> _TB_ChiTietHoaDons;
		
		private EntityRef<TB_KhachHang> _TB_KhachHang;
		
		private EntityRef<TB_NhanVien> _TB_NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHoaDonChanging(string value);
    partial void OnMaHoaDonChanged();
    partial void OnMaNhanVienChanging(string value);
    partial void OnMaNhanVienChanged();
    partial void OnMaKhachHangChanging(string value);
    partial void OnMaKhachHangChanged();
    partial void OnThoiGianChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianChanged();
    partial void OnTongTienChanging(System.Nullable<int> value);
    partial void OnTongTienChanged();
    #endregion
		
		public TB_HoaDon()
		{
			this._TB_ChiTietHoaDons = new EntitySet<TB_ChiTietHoaDon>(new Action<TB_ChiTietHoaDon>(this.attach_TB_ChiTietHoaDons), new Action<TB_ChiTietHoaDon>(this.detach_TB_ChiTietHoaDons));
			this._TB_KhachHang = default(EntityRef<TB_KhachHang>);
			this._TB_NhanVien = default(EntityRef<TB_NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoaDon", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHoaDon
		{
			get
			{
				return this._MaHoaDon;
			}
			set
			{
				if ((this._MaHoaDon != value))
				{
					this.OnMaHoaDonChanging(value);
					this.SendPropertyChanging();
					this._MaHoaDon = value;
					this.SendPropertyChanged("MaHoaDon");
					this.OnMaHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="NVarChar(10)")]
		public string MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					if (this._TB_NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="NVarChar(10)")]
		public string MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					if (this._TB_KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGian", DbType="Date")]
		public System.Nullable<System.DateTime> ThoiGian
		{
			get
			{
				return this._ThoiGian;
			}
			set
			{
				if ((this._ThoiGian != value))
				{
					this.OnThoiGianChanging(value);
					this.SendPropertyChanging();
					this._ThoiGian = value;
					this.SendPropertyChanged("ThoiGian");
					this.OnThoiGianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Int")]
		public System.Nullable<int> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_HoaDon_TB_ChiTietHoaDon", Storage="_TB_ChiTietHoaDons", ThisKey="MaHoaDon", OtherKey="MaHoaDon")]
		public EntitySet<TB_ChiTietHoaDon> TB_ChiTietHoaDons
		{
			get
			{
				return this._TB_ChiTietHoaDons;
			}
			set
			{
				this._TB_ChiTietHoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_KhachHang_TB_HoaDon", Storage="_TB_KhachHang", ThisKey="MaKhachHang", OtherKey="MaKhachHang", IsForeignKey=true, DeleteRule="SET NULL")]
		public TB_KhachHang TB_KhachHang
		{
			get
			{
				return this._TB_KhachHang.Entity;
			}
			set
			{
				TB_KhachHang previousValue = this._TB_KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._TB_KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_KhachHang.Entity = null;
						previousValue.TB_HoaDons.Remove(this);
					}
					this._TB_KhachHang.Entity = value;
					if ((value != null))
					{
						value.TB_HoaDons.Add(this);
						this._MaKhachHang = value.MaKhachHang;
					}
					else
					{
						this._MaKhachHang = default(string);
					}
					this.SendPropertyChanged("TB_KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_NhanVien_TB_HoaDon", Storage="_TB_NhanVien", ThisKey="MaNhanVien", OtherKey="MaNhanVien", IsForeignKey=true, DeleteRule="SET NULL")]
		public TB_NhanVien TB_NhanVien
		{
			get
			{
				return this._TB_NhanVien.Entity;
			}
			set
			{
				TB_NhanVien previousValue = this._TB_NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._TB_NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_NhanVien.Entity = null;
						previousValue.TB_HoaDons.Remove(this);
					}
					this._TB_NhanVien.Entity = value;
					if ((value != null))
					{
						value.TB_HoaDons.Add(this);
						this._MaNhanVien = value.MaNhanVien;
					}
					else
					{
						this._MaNhanVien = default(string);
					}
					this.SendPropertyChanged("TB_NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_ChiTietHoaDons(TB_ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.TB_HoaDon = this;
		}
		
		private void detach_TB_ChiTietHoaDons(TB_ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.TB_HoaDon = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_KhachHang")]
	public partial class TB_KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKhachHang;
		
		private string _HoTen;
		
		private string _SoDienThoai;
		
		private string _DiaChi;
		
		private EntitySet<TB_HoaDon> _TB_HoaDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhachHangChanging(string value);
    partial void OnMaKhachHangChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    #endregion
		
		public TB_KhachHang()
		{
			this._TB_HoaDons = new EntitySet<TB_HoaDon>(new Action<TB_HoaDon>(this.attach_TB_HoaDons), new Action<TB_HoaDon>(this.detach_TB_HoaDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(30)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="NVarChar(30)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(30)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_KhachHang_TB_HoaDon", Storage="_TB_HoaDons", ThisKey="MaKhachHang", OtherKey="MaKhachHang")]
		public EntitySet<TB_HoaDon> TB_HoaDons
		{
			get
			{
				return this._TB_HoaDons;
			}
			set
			{
				this._TB_HoaDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_HoaDons(TB_HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.TB_KhachHang = this;
		}
		
		private void detach_TB_HoaDons(TB_HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.TB_KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_LoaiSanPham")]
	public partial class TB_LoaiSanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoaiSanPham;
		
		private string _TenLoaiSanPham;
		
		private System.Nullable<int> _SoLuong;
		
		private EntitySet<TB_SanPham> _TB_SanPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiSanPhamChanging(string value);
    partial void OnMaLoaiSanPhamChanged();
    partial void OnTenLoaiSanPhamChanging(string value);
    partial void OnTenLoaiSanPhamChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    #endregion
		
		public TB_LoaiSanPham()
		{
			this._TB_SanPhams = new EntitySet<TB_SanPham>(new Action<TB_SanPham>(this.attach_TB_SanPhams), new Action<TB_SanPham>(this.detach_TB_SanPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiSanPham", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoaiSanPham
		{
			get
			{
				return this._MaLoaiSanPham;
			}
			set
			{
				if ((this._MaLoaiSanPham != value))
				{
					this.OnMaLoaiSanPhamChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiSanPham = value;
					this.SendPropertyChanged("MaLoaiSanPham");
					this.OnMaLoaiSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiSanPham", DbType="NVarChar(30)")]
		public string TenLoaiSanPham
		{
			get
			{
				return this._TenLoaiSanPham;
			}
			set
			{
				if ((this._TenLoaiSanPham != value))
				{
					this.OnTenLoaiSanPhamChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiSanPham = value;
					this.SendPropertyChanged("TenLoaiSanPham");
					this.OnTenLoaiSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_LoaiSanPham_TB_SanPham", Storage="_TB_SanPhams", ThisKey="MaLoaiSanPham", OtherKey="MaLoaiSanPham")]
		public EntitySet<TB_SanPham> TB_SanPhams
		{
			get
			{
				return this._TB_SanPhams;
			}
			set
			{
				this._TB_SanPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_SanPhams(TB_SanPham entity)
		{
			this.SendPropertyChanging();
			entity.TB_LoaiSanPham = this;
		}
		
		private void detach_TB_SanPhams(TB_SanPham entity)
		{
			this.SendPropertyChanging();
			entity.TB_LoaiSanPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_NguyenLieu")]
	public partial class TB_NguyenLieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNguyenLieu;
		
		private string _TenNguyenLieu;
		
		private string _MaDonVi;
		
		private System.Nullable<int> _Gia;
		
		private System.Nullable<bool> _TamKhoa;
		
		private EntitySet<TB_ChiTietNguyenLieu> _TB_ChiTietNguyenLieus;
		
		private EntityRef<TB_DonVi> _TB_DonVi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNguyenLieuChanging(string value);
    partial void OnMaNguyenLieuChanged();
    partial void OnTenNguyenLieuChanging(string value);
    partial void OnTenNguyenLieuChanged();
    partial void OnMaDonViChanging(string value);
    partial void OnMaDonViChanged();
    partial void OnGiaChanging(System.Nullable<int> value);
    partial void OnGiaChanged();
    partial void OnTamKhoaChanging(System.Nullable<bool> value);
    partial void OnTamKhoaChanged();
    #endregion
		
		public TB_NguyenLieu()
		{
			this._TB_ChiTietNguyenLieus = new EntitySet<TB_ChiTietNguyenLieu>(new Action<TB_ChiTietNguyenLieu>(this.attach_TB_ChiTietNguyenLieus), new Action<TB_ChiTietNguyenLieu>(this.detach_TB_ChiTietNguyenLieus));
			this._TB_DonVi = default(EntityRef<TB_DonVi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguyenLieu", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNguyenLieu
		{
			get
			{
				return this._MaNguyenLieu;
			}
			set
			{
				if ((this._MaNguyenLieu != value))
				{
					this.OnMaNguyenLieuChanging(value);
					this.SendPropertyChanging();
					this._MaNguyenLieu = value;
					this.SendPropertyChanged("MaNguyenLieu");
					this.OnMaNguyenLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNguyenLieu", DbType="NVarChar(30)")]
		public string TenNguyenLieu
		{
			get
			{
				return this._TenNguyenLieu;
			}
			set
			{
				if ((this._TenNguyenLieu != value))
				{
					this.OnTenNguyenLieuChanging(value);
					this.SendPropertyChanging();
					this._TenNguyenLieu = value;
					this.SendPropertyChanged("TenNguyenLieu");
					this.OnTenNguyenLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonVi", DbType="NVarChar(10)")]
		public string MaDonVi
		{
			get
			{
				return this._MaDonVi;
			}
			set
			{
				if ((this._MaDonVi != value))
				{
					if (this._TB_DonVi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDonViChanging(value);
					this.SendPropertyChanging();
					this._MaDonVi = value;
					this.SendPropertyChanged("MaDonVi");
					this.OnMaDonViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Int")]
		public System.Nullable<int> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TamKhoa", DbType="Bit")]
		public System.Nullable<bool> TamKhoa
		{
			get
			{
				return this._TamKhoa;
			}
			set
			{
				if ((this._TamKhoa != value))
				{
					this.OnTamKhoaChanging(value);
					this.SendPropertyChanging();
					this._TamKhoa = value;
					this.SendPropertyChanged("TamKhoa");
					this.OnTamKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_NguyenLieu_TB_ChiTietNguyenLieu", Storage="_TB_ChiTietNguyenLieus", ThisKey="MaNguyenLieu", OtherKey="MaNguyenLieu")]
		public EntitySet<TB_ChiTietNguyenLieu> TB_ChiTietNguyenLieus
		{
			get
			{
				return this._TB_ChiTietNguyenLieus;
			}
			set
			{
				this._TB_ChiTietNguyenLieus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_DonVi_TB_NguyenLieu", Storage="_TB_DonVi", ThisKey="MaDonVi", OtherKey="MaDonVi", IsForeignKey=true, DeleteRule="SET NULL")]
		public TB_DonVi TB_DonVi
		{
			get
			{
				return this._TB_DonVi.Entity;
			}
			set
			{
				TB_DonVi previousValue = this._TB_DonVi.Entity;
				if (((previousValue != value) 
							|| (this._TB_DonVi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_DonVi.Entity = null;
						previousValue.TB_NguyenLieus.Remove(this);
					}
					this._TB_DonVi.Entity = value;
					if ((value != null))
					{
						value.TB_NguyenLieus.Add(this);
						this._MaDonVi = value.MaDonVi;
					}
					else
					{
						this._MaDonVi = default(string);
					}
					this.SendPropertyChanged("TB_DonVi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_ChiTietNguyenLieus(TB_ChiTietNguyenLieu entity)
		{
			this.SendPropertyChanging();
			entity.TB_NguyenLieu = this;
		}
		
		private void detach_TB_ChiTietNguyenLieus(TB_ChiTietNguyenLieu entity)
		{
			this.SendPropertyChanging();
			entity.TB_NguyenLieu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_NhanVien")]
	public partial class TB_NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhanVien;
		
		private string _HoTen;
		
		private string _GioiTinh;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _CMND;
		
		private string _SoDienThoai;
		
		private string _DiaChi;
		
		private System.Nullable<System.DateTime> _NgayVaoLam;
		
		private string _ChucVu;
		
		private string _MucLuong;
		
		private string _MaQuay;
		
		private System.Nullable<bool> _TamKhoa;
		
		private EntitySet<TB_TaiKhoan> _TB_TaiKhoans;
		
		private EntitySet<TB_HoaDon> _TB_HoaDons;
		
		private EntityRef<TB_Quay> _TB_Quay;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhanVienChanging(string value);
    partial void OnMaNhanVienChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnNgayVaoLamChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayVaoLamChanged();
    partial void OnChucVuChanging(string value);
    partial void OnChucVuChanged();
    partial void OnMucLuongChanging(string value);
    partial void OnMucLuongChanged();
    partial void OnMaQuayChanging(string value);
    partial void OnMaQuayChanged();
    partial void OnTamKhoaChanging(System.Nullable<bool> value);
    partial void OnTamKhoaChanged();
    #endregion
		
		public TB_NhanVien()
		{
			this._TB_TaiKhoans = new EntitySet<TB_TaiKhoan>(new Action<TB_TaiKhoan>(this.attach_TB_TaiKhoans), new Action<TB_TaiKhoan>(this.detach_TB_TaiKhoans));
			this._TB_HoaDons = new EntitySet<TB_HoaDon>(new Action<TB_HoaDon>(this.attach_TB_HoaDons), new Action<TB_HoaDon>(this.detach_TB_HoaDons));
			this._TB_Quay = default(EntityRef<TB_Quay>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(30)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(30)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="NVarChar(30)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="NVarChar(30)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(30)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayVaoLam", DbType="Date")]
		public System.Nullable<System.DateTime> NgayVaoLam
		{
			get
			{
				return this._NgayVaoLam;
			}
			set
			{
				if ((this._NgayVaoLam != value))
				{
					this.OnNgayVaoLamChanging(value);
					this.SendPropertyChanging();
					this._NgayVaoLam = value;
					this.SendPropertyChanged("NgayVaoLam");
					this.OnNgayVaoLamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="NVarChar(30)")]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this.OnChucVuChanging(value);
					this.SendPropertyChanging();
					this._ChucVu = value;
					this.SendPropertyChanged("ChucVu");
					this.OnChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MucLuong", DbType="NVarChar(30)")]
		public string MucLuong
		{
			get
			{
				return this._MucLuong;
			}
			set
			{
				if ((this._MucLuong != value))
				{
					this.OnMucLuongChanging(value);
					this.SendPropertyChanging();
					this._MucLuong = value;
					this.SendPropertyChanged("MucLuong");
					this.OnMucLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQuay", DbType="NVarChar(10)")]
		public string MaQuay
		{
			get
			{
				return this._MaQuay;
			}
			set
			{
				if ((this._MaQuay != value))
				{
					if (this._TB_Quay.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaQuayChanging(value);
					this.SendPropertyChanging();
					this._MaQuay = value;
					this.SendPropertyChanged("MaQuay");
					this.OnMaQuayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TamKhoa", DbType="Bit")]
		public System.Nullable<bool> TamKhoa
		{
			get
			{
				return this._TamKhoa;
			}
			set
			{
				if ((this._TamKhoa != value))
				{
					this.OnTamKhoaChanging(value);
					this.SendPropertyChanging();
					this._TamKhoa = value;
					this.SendPropertyChanged("TamKhoa");
					this.OnTamKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_NhanVien_TB_TaiKhoan", Storage="_TB_TaiKhoans", ThisKey="MaNhanVien", OtherKey="MaNhanVien")]
		public EntitySet<TB_TaiKhoan> TB_TaiKhoans
		{
			get
			{
				return this._TB_TaiKhoans;
			}
			set
			{
				this._TB_TaiKhoans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_NhanVien_TB_HoaDon", Storage="_TB_HoaDons", ThisKey="MaNhanVien", OtherKey="MaNhanVien")]
		public EntitySet<TB_HoaDon> TB_HoaDons
		{
			get
			{
				return this._TB_HoaDons;
			}
			set
			{
				this._TB_HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Quay_TB_NhanVien", Storage="_TB_Quay", ThisKey="MaQuay", OtherKey="MaQuay", IsForeignKey=true, DeleteRule="SET NULL")]
		public TB_Quay TB_Quay
		{
			get
			{
				return this._TB_Quay.Entity;
			}
			set
			{
				TB_Quay previousValue = this._TB_Quay.Entity;
				if (((previousValue != value) 
							|| (this._TB_Quay.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_Quay.Entity = null;
						previousValue.TB_NhanViens.Remove(this);
					}
					this._TB_Quay.Entity = value;
					if ((value != null))
					{
						value.TB_NhanViens.Add(this);
						this._MaQuay = value.MaQuay;
					}
					else
					{
						this._MaQuay = default(string);
					}
					this.SendPropertyChanged("TB_Quay");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_TaiKhoans(TB_TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.TB_NhanVien = this;
		}
		
		private void detach_TB_TaiKhoans(TB_TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.TB_NhanVien = null;
		}
		
		private void attach_TB_HoaDons(TB_HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.TB_NhanVien = this;
		}
		
		private void detach_TB_HoaDons(TB_HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.TB_NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_Quay")]
	public partial class TB_Quay : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaQuay;
		
		private string _TenQuay;
		
		private System.Nullable<int> _SoLuongNhanVien;
		
		private EntitySet<TB_NhanVien> _TB_NhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaQuayChanging(string value);
    partial void OnMaQuayChanged();
    partial void OnTenQuayChanging(string value);
    partial void OnTenQuayChanged();
    partial void OnSoLuongNhanVienChanging(System.Nullable<int> value);
    partial void OnSoLuongNhanVienChanged();
    #endregion
		
		public TB_Quay()
		{
			this._TB_NhanViens = new EntitySet<TB_NhanVien>(new Action<TB_NhanVien>(this.attach_TB_NhanViens), new Action<TB_NhanVien>(this.detach_TB_NhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQuay", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaQuay
		{
			get
			{
				return this._MaQuay;
			}
			set
			{
				if ((this._MaQuay != value))
				{
					this.OnMaQuayChanging(value);
					this.SendPropertyChanging();
					this._MaQuay = value;
					this.SendPropertyChanged("MaQuay");
					this.OnMaQuayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQuay", DbType="NVarChar(30)")]
		public string TenQuay
		{
			get
			{
				return this._TenQuay;
			}
			set
			{
				if ((this._TenQuay != value))
				{
					this.OnTenQuayChanging(value);
					this.SendPropertyChanging();
					this._TenQuay = value;
					this.SendPropertyChanged("TenQuay");
					this.OnTenQuayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongNhanVien", DbType="Int")]
		public System.Nullable<int> SoLuongNhanVien
		{
			get
			{
				return this._SoLuongNhanVien;
			}
			set
			{
				if ((this._SoLuongNhanVien != value))
				{
					this.OnSoLuongNhanVienChanging(value);
					this.SendPropertyChanging();
					this._SoLuongNhanVien = value;
					this.SendPropertyChanged("SoLuongNhanVien");
					this.OnSoLuongNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Quay_TB_NhanVien", Storage="_TB_NhanViens", ThisKey="MaQuay", OtherKey="MaQuay")]
		public EntitySet<TB_NhanVien> TB_NhanViens
		{
			get
			{
				return this._TB_NhanViens;
			}
			set
			{
				this._TB_NhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_NhanViens(TB_NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.TB_Quay = this;
		}
		
		private void detach_TB_NhanViens(TB_NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.TB_Quay = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_SanPham")]
	public partial class TB_SanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSanPham;
		
		private string _TenSanPham;
		
		private System.Nullable<int> _Gia;
		
		private string _MaDonVi;
		
		private string _MaLoaiSanPham;
		
		private System.Nullable<bool> _TamKhoa;
		
		private EntitySet<TB_ChiTietHoaDon> _TB_ChiTietHoaDons;
		
		private EntitySet<TB_ChiTietNguyenLieu> _TB_ChiTietNguyenLieus;
		
		private EntityRef<TB_DonVi> _TB_DonVi;
		
		private EntityRef<TB_LoaiSanPham> _TB_LoaiSanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSanPhamChanging(string value);
    partial void OnMaSanPhamChanged();
    partial void OnTenSanPhamChanging(string value);
    partial void OnTenSanPhamChanged();
    partial void OnGiaChanging(System.Nullable<int> value);
    partial void OnGiaChanged();
    partial void OnMaDonViChanging(string value);
    partial void OnMaDonViChanged();
    partial void OnMaLoaiSanPhamChanging(string value);
    partial void OnMaLoaiSanPhamChanged();
    partial void OnTamKhoaChanging(System.Nullable<bool> value);
    partial void OnTamKhoaChanged();
    #endregion
		
		public TB_SanPham()
		{
			this._TB_ChiTietHoaDons = new EntitySet<TB_ChiTietHoaDon>(new Action<TB_ChiTietHoaDon>(this.attach_TB_ChiTietHoaDons), new Action<TB_ChiTietHoaDon>(this.detach_TB_ChiTietHoaDons));
			this._TB_ChiTietNguyenLieus = new EntitySet<TB_ChiTietNguyenLieu>(new Action<TB_ChiTietNguyenLieu>(this.attach_TB_ChiTietNguyenLieus), new Action<TB_ChiTietNguyenLieu>(this.detach_TB_ChiTietNguyenLieus));
			this._TB_DonVi = default(EntityRef<TB_DonVi>);
			this._TB_LoaiSanPham = default(EntityRef<TB_LoaiSanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSanPham", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSanPham
		{
			get
			{
				return this._MaSanPham;
			}
			set
			{
				if ((this._MaSanPham != value))
				{
					this.OnMaSanPhamChanging(value);
					this.SendPropertyChanging();
					this._MaSanPham = value;
					this.SendPropertyChanged("MaSanPham");
					this.OnMaSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSanPham", DbType="NVarChar(30)")]
		public string TenSanPham
		{
			get
			{
				return this._TenSanPham;
			}
			set
			{
				if ((this._TenSanPham != value))
				{
					this.OnTenSanPhamChanging(value);
					this.SendPropertyChanging();
					this._TenSanPham = value;
					this.SendPropertyChanged("TenSanPham");
					this.OnTenSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Int")]
		public System.Nullable<int> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonVi", DbType="NVarChar(10)")]
		public string MaDonVi
		{
			get
			{
				return this._MaDonVi;
			}
			set
			{
				if ((this._MaDonVi != value))
				{
					if (this._TB_DonVi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDonViChanging(value);
					this.SendPropertyChanging();
					this._MaDonVi = value;
					this.SendPropertyChanged("MaDonVi");
					this.OnMaDonViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiSanPham", DbType="NVarChar(10)")]
		public string MaLoaiSanPham
		{
			get
			{
				return this._MaLoaiSanPham;
			}
			set
			{
				if ((this._MaLoaiSanPham != value))
				{
					if (this._TB_LoaiSanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiSanPhamChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiSanPham = value;
					this.SendPropertyChanged("MaLoaiSanPham");
					this.OnMaLoaiSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TamKhoa", DbType="Bit")]
		public System.Nullable<bool> TamKhoa
		{
			get
			{
				return this._TamKhoa;
			}
			set
			{
				if ((this._TamKhoa != value))
				{
					this.OnTamKhoaChanging(value);
					this.SendPropertyChanging();
					this._TamKhoa = value;
					this.SendPropertyChanged("TamKhoa");
					this.OnTamKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_SanPham_TB_ChiTietHoaDon", Storage="_TB_ChiTietHoaDons", ThisKey="MaSanPham", OtherKey="MaSanPham")]
		public EntitySet<TB_ChiTietHoaDon> TB_ChiTietHoaDons
		{
			get
			{
				return this._TB_ChiTietHoaDons;
			}
			set
			{
				this._TB_ChiTietHoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_SanPham_TB_ChiTietNguyenLieu", Storage="_TB_ChiTietNguyenLieus", ThisKey="MaSanPham", OtherKey="MaSanPham")]
		public EntitySet<TB_ChiTietNguyenLieu> TB_ChiTietNguyenLieus
		{
			get
			{
				return this._TB_ChiTietNguyenLieus;
			}
			set
			{
				this._TB_ChiTietNguyenLieus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_DonVi_TB_SanPham", Storage="_TB_DonVi", ThisKey="MaDonVi", OtherKey="MaDonVi", IsForeignKey=true, DeleteRule="SET NULL")]
		public TB_DonVi TB_DonVi
		{
			get
			{
				return this._TB_DonVi.Entity;
			}
			set
			{
				TB_DonVi previousValue = this._TB_DonVi.Entity;
				if (((previousValue != value) 
							|| (this._TB_DonVi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_DonVi.Entity = null;
						previousValue.TB_SanPhams.Remove(this);
					}
					this._TB_DonVi.Entity = value;
					if ((value != null))
					{
						value.TB_SanPhams.Add(this);
						this._MaDonVi = value.MaDonVi;
					}
					else
					{
						this._MaDonVi = default(string);
					}
					this.SendPropertyChanged("TB_DonVi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_LoaiSanPham_TB_SanPham", Storage="_TB_LoaiSanPham", ThisKey="MaLoaiSanPham", OtherKey="MaLoaiSanPham", IsForeignKey=true, DeleteRule="SET NULL")]
		public TB_LoaiSanPham TB_LoaiSanPham
		{
			get
			{
				return this._TB_LoaiSanPham.Entity;
			}
			set
			{
				TB_LoaiSanPham previousValue = this._TB_LoaiSanPham.Entity;
				if (((previousValue != value) 
							|| (this._TB_LoaiSanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_LoaiSanPham.Entity = null;
						previousValue.TB_SanPhams.Remove(this);
					}
					this._TB_LoaiSanPham.Entity = value;
					if ((value != null))
					{
						value.TB_SanPhams.Add(this);
						this._MaLoaiSanPham = value.MaLoaiSanPham;
					}
					else
					{
						this._MaLoaiSanPham = default(string);
					}
					this.SendPropertyChanged("TB_LoaiSanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_ChiTietHoaDons(TB_ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.TB_SanPham = this;
		}
		
		private void detach_TB_ChiTietHoaDons(TB_ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.TB_SanPham = null;
		}
		
		private void attach_TB_ChiTietNguyenLieus(TB_ChiTietNguyenLieu entity)
		{
			this.SendPropertyChanging();
			entity.TB_SanPham = this;
		}
		
		private void detach_TB_ChiTietNguyenLieus(TB_ChiTietNguyenLieu entity)
		{
			this.SendPropertyChanging();
			entity.TB_SanPham = null;
		}
	}
	
	public partial class ufuLayHoaDonResult
	{
		
		private string _MaHoaDon;
		
		private string _TenNhanVien;
		
		private string _TenKhachHang;
		
		private System.Nullable<System.DateTime> _ThoiGian;
		
		private System.Nullable<int> _TongTien;
		
		public ufuLayHoaDonResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoaDon", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MaHoaDon
		{
			get
			{
				return this._MaHoaDon;
			}
			set
			{
				if ((this._MaHoaDon != value))
				{
					this._MaHoaDon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhanVien", DbType="NVarChar(30)")]
		public string TenNhanVien
		{
			get
			{
				return this._TenNhanVien;
			}
			set
			{
				if ((this._TenNhanVien != value))
				{
					this._TenNhanVien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhachHang", DbType="NVarChar(30)")]
		public string TenKhachHang
		{
			get
			{
				return this._TenKhachHang;
			}
			set
			{
				if ((this._TenKhachHang != value))
				{
					this._TenKhachHang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGian", DbType="Date")]
		public System.Nullable<System.DateTime> ThoiGian
		{
			get
			{
				return this._ThoiGian;
			}
			set
			{
				if ((this._ThoiGian != value))
				{
					this._ThoiGian = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Int")]
		public System.Nullable<int> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this._TongTien = value;
				}
			}
		}
	}
	
	public partial class ufuLocHoaDonResult
	{
		
		private string _MaHoaDon;
		
		private string _MaNhanVien;
		
		private string _MaKhachHang;
		
		private System.Nullable<System.DateTime> _ThoiGian;
		
		private System.Nullable<int> _TongTien;
		
		public ufuLocHoaDonResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoaDon", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MaHoaDon
		{
			get
			{
				return this._MaHoaDon;
			}
			set
			{
				if ((this._MaHoaDon != value))
				{
					this._MaHoaDon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="NVarChar(10)")]
		public string MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					this._MaNhanVien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="NVarChar(10)")]
		public string MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					this._MaKhachHang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGian", DbType="Date")]
		public System.Nullable<System.DateTime> ThoiGian
		{
			get
			{
				return this._ThoiGian;
			}
			set
			{
				if ((this._ThoiGian != value))
				{
					this._ThoiGian = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Int")]
		public System.Nullable<int> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this._TongTien = value;
				}
			}
		}
	}
	
	public partial class ufuThongKeDoanhThuThangResult
	{
		
		private string _Tháng;
		
		private string _Năm;
		
		private System.Nullable<int> _Tiền_Thu_Vào;
		
		private System.Nullable<int> _Tiền_Chi_Ra;
		
		private System.Nullable<int> _Tiền_Lời;
		
		public ufuThongKeDoanhThuThangResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tháng", DbType="NVarChar(10)")]
		public string Tháng
		{
			get
			{
				return this._Tháng;
			}
			set
			{
				if ((this._Tháng != value))
				{
					this._Tháng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Năm", DbType="NVarChar(10)")]
		public string Năm
		{
			get
			{
				return this._Năm;
			}
			set
			{
				if ((this._Năm != value))
				{
					this._Năm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tiền Thu Vào]", Storage="_Tiền_Thu_Vào", DbType="Int")]
		public System.Nullable<int> Tiền_Thu_Vào
		{
			get
			{
				return this._Tiền_Thu_Vào;
			}
			set
			{
				if ((this._Tiền_Thu_Vào != value))
				{
					this._Tiền_Thu_Vào = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tiền Chi Ra]", Storage="_Tiền_Chi_Ra", DbType="Int")]
		public System.Nullable<int> Tiền_Chi_Ra
		{
			get
			{
				return this._Tiền_Chi_Ra;
			}
			set
			{
				if ((this._Tiền_Chi_Ra != value))
				{
					this._Tiền_Chi_Ra = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tiền Lời]", Storage="_Tiền_Lời", DbType="Int")]
		public System.Nullable<int> Tiền_Lời
		{
			get
			{
				return this._Tiền_Lời;
			}
			set
			{
				if ((this._Tiền_Lời != value))
				{
					this._Tiền_Lời = value;
				}
			}
		}
	}
	
	public partial class ufuTimKiemNhanVienTheoTenResult
	{
		
		private string _MaNhanVien;
		
		private string _HoTen;
		
		private string _GioiTinh;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _CMND;
		
		private string _SoDienThoai;
		
		private string _DiaChi;
		
		private System.Nullable<System.DateTime> _NgayVaoLam;
		
		private string _ChucVu;
		
		private string _MucLuong;
		
		private string _TenQuay;
		
		private System.Nullable<bool> _TamKhoa;
		
		public ufuTimKiemNhanVienTheoTenResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					this._MaNhanVien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(30)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(30)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this._GioiTinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this._NgaySinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="NVarChar(30)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this._CMND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="NVarChar(30)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this._SoDienThoai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(30)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayVaoLam", DbType="Date")]
		public System.Nullable<System.DateTime> NgayVaoLam
		{
			get
			{
				return this._NgayVaoLam;
			}
			set
			{
				if ((this._NgayVaoLam != value))
				{
					this._NgayVaoLam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="NVarChar(30)")]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this._ChucVu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MucLuong", DbType="NVarChar(30)")]
		public string MucLuong
		{
			get
			{
				return this._MucLuong;
			}
			set
			{
				if ((this._MucLuong != value))
				{
					this._MucLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQuay", DbType="NVarChar(30)")]
		public string TenQuay
		{
			get
			{
				return this._TenQuay;
			}
			set
			{
				if ((this._TenQuay != value))
				{
					this._TenQuay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TamKhoa", DbType="Bit")]
		public System.Nullable<bool> TamKhoa
		{
			get
			{
				return this._TamKhoa;
			}
			set
			{
				if ((this._TamKhoa != value))
				{
					this._TamKhoa = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
